name: alarm
description: A simple Flutter alarm manager plugin for both iOS and Android.
version: 2.1.0
homepage: https://github.com/gdelataillade/alarm

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  android_alarm_manager_plus: ^3.0.1
  flutter:
    sdk: flutter
  flutter_fgbg: ^0.3.0
  flutter_local_notifications: ^16.2.0
  just_audio: ^0.9.34
  plugin_platform_interface: ^2.1.4
  shared_preferences: ^2.1.2  
  timezone: ^0.9.2
  vibration: ^1.8.1
  volume_controller: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/long_blank.mp3

  plugin:
    platforms:
      android:
        package: com.gdelataillade.alarm.alarm
        pluginClass: AlarmPlugin
      ios:
        pluginClass: AlarmPlugin